// GENERATED by scripts/generate.mjs — do not edit by hand.
export const SELECT_PROMPT = "Select one you enjoy";

export type UpperBackTag = "traps" | "rear_delt" | "mid_back";
export type ProgressionMode = "weight" | "reps";

export interface Exercise {
  name: string;
  compound: boolean;
  tags: UpperBackTag[];
  incrementKg: number;
  progressionMode: ProgressionMode;
}

export interface Pattern {
  slug: string;
  muscle: string;
  name: string;
  optional: boolean;
  prompt: string;
  exercises: Exercise[];
}

export const PATTERNS: Pattern[] = [
  {
    "slug": "quads-press",
    "muscle": "Quads",
    "name": "Quads — Pressing",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Squat",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Hack squat",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Pendulum squat",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Front squat",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Leg press",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "quads-ext",
    "muscle": "Quads",
    "name": "Quads — Extension",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Leg extension machine",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Free weight leg extension",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "hip-hinge",
    "muscle": "Posterior chain",
    "name": "Hip hinge",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Romanian deadlift",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Hip thrust",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Stiff leg deadlift",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      },
      {
        "name": "Back extension",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "ham-curl",
    "muscle": "Hamstrings",
    "name": "Hamstring curl",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Seated hamstring curl machine",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Lying hamstring curl machine",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "calves",
    "muscle": "Calves",
    "name": "Calves",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Dumbbell calf raise",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Smith machine calf raise",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Calf raise on leg press",
        "compound": false,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "lats-vertical",
    "muscle": "Lats",
    "name": "Lats — Vertical pull",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Weighted pull ups",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Bodyweight pull ups",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "reps"
      },
      {
        "name": "Assisted pull ups",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Lat pulldown",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "lats-horizontal",
    "muscle": "Lats",
    "name": "Lats — Horizontal pull",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Chest supported row (normal grip)",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Cable row (medium grip)",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell row",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "mid-chest",
    "muscle": "Chest",
    "name": "Mid chest",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Pec deck",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell fly",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Flat barbell bench press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Flat dumbbell bench press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Smith machine flat bench press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Machine chest press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "upper-chest",
    "muscle": "Chest",
    "name": "Upper chest",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Incline dumbbell press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Incline smith machine press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Incline barbell press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Low to high fly",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "overhead-press",
    "muscle": "Shoulders",
    "name": "Overhead press",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Standing overhead barbell press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Shoulder press (pin-loaded machine)",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Shoulder press (free-weight machine)",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Seated dumbbell shoulder press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Seated barbell shoulder press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "side-delts",
    "muscle": "Side delts",
    "name": "Side delts",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Dumbbell lateral raise",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Cable lateral raise",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Machine lateral raise",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "upper-back-combo",
    "muscle": "Traps / Rear delt / Mid back",
    "name": "Traps / Rear delt / Mid back",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Wide grip flared-elbow row",
        "compound": true,
        "tags": ["traps", "rear_delt", "mid_back"],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Kelso shrug",
        "compound": false,
        "tags": ["traps", "rear_delt", "mid_back"],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Close grip cable row",
        "compound": true,
        "tags": ["traps", "rear_delt", "mid_back"],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Face pull",
        "compound": false,
        "tags": ["traps", "rear_delt"],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Rear delt fly machine",
        "compound": false,
        "tags": ["rear_delt"],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell reverse fly",
        "compound": false,
        "tags": ["rear_delt"],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Cable reverse fly",
        "compound": false,
        "tags": ["rear_delt"],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell shrug",
        "compound": false,
        "tags": ["traps"],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Smith machine shrug",
        "compound": false,
        "tags": ["traps"],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "triceps-overhead",
    "muscle": "Triceps",
    "name": "Triceps — Overhead / side",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Overhead cable extension",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Bodyweight dips",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "reps"
      },
      {
        "name": "Weighted dips",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Single-arm tricep extension",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell skull crusher",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Barbell / EZ-bar skull crusher",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell French press",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "triceps-near-torso",
    "muscle": "Triceps",
    "name": "Triceps — Near-torso",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Cable tricep pushdown",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Rope pushdown",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Barbell JM press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Smith machine JM press",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "biceps",
    "muscle": "Biceps",
    "name": "Biceps",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Dumbbell curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell preacher curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Barbell curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Barbell preacher curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Incline dumbbell curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Spider curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Cable curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Bayesian curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "brachioradialis",
    "muscle": "Brachioradialis",
    "name": "Brachioradialis",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Dumbbell hammer curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Cable hammer curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Dumbbell reverse curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Cable reverse curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Barbell reverse curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "abs",
    "muscle": "Abs",
    "name": "Abs",
    "optional": false,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Cable crunch",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Ab crunch machine",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Weighted decline sit-up",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Weighted sit-up",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "forearm-flexors",
    "muscle": "Forearms",
    "name": "Forearms — Flexors",
    "optional": true,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Dumbbell supinated wrist curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "EZ-bar supinated wrist curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      },
      {
        "name": "Cable supinated wrist curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "forearm-extensors",
    "muscle": "Forearms",
    "name": "Forearms — Extensors",
    "optional": true,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Dumbbell pronated wrist curl",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "glute-iso",
    "muscle": "Glutes",
    "name": "Glute isolation",
    "optional": true,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Glute kickback",
        "compound": false,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "Extra hip thrust",
        "compound": true,
        "tags": [],
        "incrementKg": 5,
        "progressionMode": "weight"
      }
    ]
  },
  {
    "slug": "lower-chest-iso",
    "muscle": "Chest",
    "name": "Lower chest isolation",
    "optional": true,
    "prompt": "Select one you enjoy",
    "exercises": [
      {
        "name": "Decline bench",
        "compound": true,
        "tags": [],
        "incrementKg": 2.5,
        "progressionMode": "weight"
      },
      {
        "name": "High to low fly",
        "compound": false,
        "tags": [],
        "incrementKg": 1,
        "progressionMode": "weight"
      }
    ]
  }
];

export const PATTERNS_BY_SLUG: Record<string, Pattern> = Object.fromEntries(
  PATTERNS.map((p) => [p.slug, p])
);

export const REQUIRED_PATTERNS = PATTERNS.filter((p) => !p.optional);
export const OPTIONAL_PATTERNS = PATTERNS.filter((p) => p.optional);