import { writeFileSync } from "node:fs";
import { PATTERNS, PROMPT } from "../lib/catalog.mjs";

const sqlStr = (s) => "'" + String(s).replace(/'/g, "''") + "'";

let sql = `-- GENERATED by scripts/generate.mjs — do not edit by hand.
-- Run after schema.sql. Idempotent: safe to re-run.

begin;

`;
for (const p of PATTERNS) {
  sql += `insert into patterns (slug, muscle, name, prompt, optional) values (${sqlStr(
    p.slug
  )}, ${sqlStr(p.muscle)}, ${sqlStr(p.name)}, ${sqlStr(PROMPT)}, ${!!p.optional})\n`;
  sql += `  on conflict (slug) do update set muscle = excluded.muscle, name = excluded.name, prompt = excluded.prompt, optional = excluded.optional;\n`;
}

sql += "\n";
const liveTuples = [];
for (const p of PATTERNS) {
  for (const e of p.exercises) {
    const tags = e.tags && e.tags.length ? `array[${e.tags.map(sqlStr).join(", ")}]::text[]` : "'{}'::text[]";
    const mode = e.mode ?? "weight";
    liveTuples.push(`(${sqlStr(p.slug)}, ${sqlStr(e.name)})`);
    sql += `insert into exercises (pattern_slug, name, compound, tags, increment_kg, progression_mode, retired) values (${sqlStr(
      p.slug
    )}, ${sqlStr(e.name)}, ${!!e.compound}, ${tags}, ${e.inc}, ${sqlStr(mode)}, false)\n`;
    sql += `  on conflict (pattern_slug, name) do update set compound = excluded.compound, tags = excluded.tags, increment_kg = excluded.increment_kg, progression_mode = excluded.progression_mode, retired = false;\n`;
  }
}

sql += `
-- Retire exercises removed from the catalog (keeps history, forces re-pick).
update exercises set retired = true
  where (pattern_slug, name) not in (${liveTuples.join(", ")});

delete from user_exercise_choices
  where exercise_id in (select id from exercises where retired = true);
`;

sql += "\ncommit;\n";
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);

console.log("wrote supabase/seed.sql");
